#!/usr/bin/env python3
"""
Add new alert phrases without disturbing the existing ones
==========================================================

The main generator re-renders all 43 clips and writes them WITHOUT the chime,
so running it would silently strip the chime off every existing alert. This
does only the phrases listed in NEW and leaves everything else untouched.

Pipeline:
    edge-tts  ->  alerts/voice_raw/<name>.mp3   (bare voice)
    ffmpeg    ->  alerts/<name>.mp3             (chime_a + voice mixed)

FFMPEG IS OPTIONAL HERE. Rendering needs edge-tts and the internet; mixing
needs ffmpeg. They are separate jobs, and there is no reason every machine that
renders a phrase must also have ffmpeg installed. If ffmpeg is missing this
renders the voices and writes bake_new_alerts.sh for the Pi to finish - the Pi
already has ffmpeg inside the Home Assistant container.

RUN ON THE MAC, with <HA_CONFIG_MOUNT> mounted:

    python3 "<LOCAL_PATH> automation project MD files/add_new_voices.py"
"""

import asyncio
import os
import subprocess
import sys

try:
    import edge_tts
except ImportError:
    sys.exit("edge-tts is not installed.  Run:  python3 -m pip install --user edge-tts")

VOICE = "en-GB-RyanNeural"
RATE = "-8%"
PITCH = "-4Hz"

OUT_DIR = "<HA_CONFIG_MOUNT>/www/alerts"
RAW_DIR = os.path.join(OUT_DIR, "voice_raw")
CHIME = os.path.join(RAW_DIR, "chime_a.mp3")

# Delay before the voice starts, in milliseconds. Matches the existing clips so
# the new ones do not feel different from the rest.
VOICE_DELAY_MS = 900

NEW = {
    "perimeter_vehicle":
        "Vehicle detected.",
}

FILTER = (
    "[1:a]adelay={d}|{d}[v];"
    "[0:a][v]amix=inputs=2:duration=longest:dropout_transition=0,volume=2.0[out]"
).format(d=VOICE_DELAY_MS)


async def render(name, text):
    raw = os.path.join(RAW_DIR, name + ".mp3")
    comm = edge_tts.Communicate(text, VOICE, rate=RATE, pitch=PITCH)
    await comm.save(raw)
    print("  voice   " + name + ".mp3")
    return raw


def have_ffmpeg():
    return subprocess.run(["which", "ffmpeg"], capture_output=True).returncode == 0


def bake(name, raw):
    """Chime plays first, voice fades in over the tail of it."""
    final = os.path.join(OUT_DIR, name + ".mp3")
    subprocess.run(
        ["ffmpeg", "-y", "-loglevel", "error", "-i", CHIME, "-i", raw,
         "-filter_complex", FILTER, "-map", "[out]",
         "-codec:a", "libmp3lame", "-q:a", "3", final],
        check=True,
    )
    print("  chimed  " + name + ".mp3")


def write_pi_bake_script(names):
    """Emit a script the Pi can run to do the mixing."""
    config_dir = os.path.dirname(os.path.dirname(OUT_DIR))   # .../<HA_CONFIG_MOUNT>
    path = os.path.join(config_dir, "bake_new_alerts.sh")
    body = [
        "#!/bin/sh",
        "# Generated by add_new_voices.py - run on the Pi:",
        "#   sh /home/<USER>/homeassistant/config/bake_new_alerts.sh",
        "set -e",
        "A=/config/www/alerts",
        "for n in " + " ".join(names) + "; do",
        '  docker exec homeassistant ffmpeg -y -loglevel error \\',
        '    -i "$A/voice_raw/chime_a.mp3" -i "$A/voice_raw/$n.mp3" \\',
        '    -filter_complex "' + FILTER + '" \\',
        '    -map "[out]" -codec:a libmp3lame -q:a 3 "$A/$n.mp3"',
        '  echo "  chimed  $n.mp3"',
        "done",
        'echo "Done."',
    ]
    with open(path, "w") as f:
        f.write("\n".join(body) + "\n")
    return path


async def main():
    if not os.path.isdir(OUT_DIR):
        sys.exit("Cannot see " + OUT_DIR + " - is the <HA_CONFIG_MOUNT> share mounted?")
    if not os.path.isfile(CHIME):
        sys.exit("Chime missing: " + CHIME)

    os.makedirs(RAW_DIR, exist_ok=True)
    can_bake = have_ffmpeg()

    print("Voice:  " + VOICE)
    print("Output: " + OUT_DIR)
    print("ffmpeg: " + ("present - baking the chime here"
                        if can_bake else "MISSING - rendering voice only"))
    print()

    for name, text in NEW.items():
        raw = await render(name, text)
        if can_bake:
            bake(name, raw)

    print()
    if can_bake:
        print("Done. " + str(len(NEW)) + " clips added, nothing else touched.")
    else:
        script = write_pi_bake_script(list(NEW))
        print(str(len(NEW)) + " voice files rendered into " + RAW_DIR)
        print("They have NO chime yet and are NOT live.")
        print()
        print("Finish on the Pi with:")
        print("    sh /home/<USER>/homeassistant/config/bake_new_alerts.sh")
        print()
        print("(script written to " + script + ")")


if __name__ == "__main__":
    asyncio.run(main())
