#!/bin/sh
# =====================================================================
# Autoflow - take a snapshot and push it to GitHub
# =====================================================================
#
#   sh snapshot.sh "what you changed"
#
# The message is optional; without one it records the date and time.
#
# WHY THIS EXISTS RATHER THAN JUST `git commit`
#
# Half of this system lives outside the repo. relay_api.py, watchdog.py and
# the rest sit in /home/USER because that is where systemd runs them
# from. Copying them in by hand before each commit is the sort of step that
# gets skipped, and then the repo quietly stops matching reality - which is
# worse than no backup, because it looks like one.
#
# WHY THE FIXED LIST IS GONE
#
# The previous version kept a hand-written list of files to copy, with a
# comment saying anything added later must be added to the list too. Three
# programs were written after that comment - watchdog.py, dvr_alarm.py and
# the autoflow-watchdog units - and all three missed it. The comment was
# read, understood, and still not followed, which is what happens to every
# instruction that competes with getting the actual work done.
#
# So nothing is listed now. Every .py and .sh in /home/USER is taken,
# and every systemd unit that mentions /home/USER is taken with it.
# Adding a new program to the system is now enough to get it backed up.

set -e

REPO=/home/USER/homeassistant
HOSTDIR="$REPO/host"
SRC=/home/USER

cd "$REPO"

# --- refuse to push anywhere except the intended private repository ---
# This script sweeps the entire home directory - real addresses, real
# camera names, host config - and pushes the result. That is safe only
# while origin points at a private repository. Repositories get renamed,
# deleted and recreated; origin does not follow them, it simply resolves
# to whatever answers to that name today. Pin it here and the question
# can never come up again.
EXPECTED_ORIGIN="git@github.com:YOUR_USERNAME/YOUR_PRIVATE_REPO.git"
ACTUAL_ORIGIN=$(git remote get-url origin 2>/dev/null || true)
if [ "$ACTUAL_ORIGIN" != "$EXPECTED_ORIGIN" ]; then
    echo "REFUSING TO RUN: origin is '$ACTUAL_ORIGIN'" >&2
    echo "Expected '$EXPECTED_ORIGIN'." >&2
    echo "Edit EXPECTED_ORIGIN above if this is deliberate." >&2
    exit 1
fi

mkdir -p "$HOSTDIR" "$HOSTDIR/systemd"

# --- programs --------------------------------------------------------
# Credentials are skipped by name. The target repository is private, but
# "private" is a setting someone can change later, and a leaked key cannot
# be un-leaked.
NPROG=0
SKIPPED=""
for f in "$SRC"/*.py "$SRC"/*.sh; do
    [ -f "$f" ] || continue
    b=$(basename "$f")
    case "$b" in
        *secret*|*credential*|*token*|*password*|*-key*|*_key*)
            SKIPPED="$SKIPPED $b"
            continue
            ;;
    esac
    cp -p "$f" "$HOSTDIR/$b"
    NPROG=$((NPROG + 1))
done

# --- systemd units ---------------------------------------------------
# Matched by content, not by name: if a unit runs something out of
# /home/USER it belongs to this project and needs saving.
NUNIT=0
for u in /etc/systemd/system/*.service /etc/systemd/system/*.timer; do
    [ -f "$u" ] || continue
    if grep -q "/home/USER" "$u" 2>/dev/null; then
        cp -p "$u" "$HOSTDIR/systemd/$(basename "$u")"
        NUNIT=$((NUNIT + 1))
    fi
done

# --- crontabs --------------------------------------------------------
# The backup and the brightness bridge are both started from root's crontab.
# Without it a restored system has the files but nothing runs them.
CRONWARN=""
TMPC=$(mktemp)

if sudo -n crontab -l -u root >"$TMPC" 2>/dev/null && [ -s "$TMPC" ]; then
    cp "$TMPC" "$HOSTDIR/crontab.root.txt"
elif [ ! -f "$HOSTDIR/crontab.root.txt" ]; then
    # Never captured. Say so loudly - a missing crontab is invisible until
    # the day it matters.
    CRONWARN=1
fi

if crontab -l >"$TMPC" 2>/dev/null && [ -s "$TMPC" ]; then
    cp "$TMPC" "$HOSTDIR/crontab.USER.txt"
fi
rm -f "$TMPC"

# A timer names the service it triggers and contains no path, so the grep
# above never matches one. Take the siblings of everything already taken.
for s in "$HOSTDIR"/systemd/*.service; do
    [ -f "$s" ] || continue
    stem=$(basename "$s" .service)
    for ext in timer socket path; do
        sib="/etc/systemd/system/$stem.$ext"
        if [ -f "$sib" ] && [ ! -f "$HOSTDIR/systemd/$stem.$ext" ]; then
            cp -p "$sib" "$HOSTDIR/systemd/$stem.$ext"
            NUNIT=$((NUNIT + 1))
        elif [ -f "$sib" ]; then
            cp -p "$sib" "$HOSTDIR/systemd/$stem.$ext"
        fi
    done
done

# A unit file does not say whether it starts at boot. That is a symlink in
# /etc/systemd/system/*.wants, and nothing here copies those. Write it down.
{
    echo "# Generated by snapshot.sh - $(date '+%Y-%m-%d %H:%M')"
    echo "# After a restore, re-enable anything marked enabled below:"
    echo "#     sudo systemctl enable --now <name>"
    echo
    for s in "$HOSTDIR"/systemd/*.service "$HOSTDIR"/systemd/*.timer; do
        [ -f "$s" ] || continue
        n=$(basename "$s")
        printf '%-34s %s\n' "$n" "$(systemctl is-enabled "$n" 2>/dev/null || echo unknown)"
    done
    echo
    printf '%-34s %s\n' docker.service \
        "$(systemctl is-enabled docker.service 2>/dev/null || echo unknown)"
    echo
    echo "# container restart policies - HA must be unless-stopped or it will"
    echo "# not come back after a power cut"
    docker inspect --format '{{.Name}} {{.HostConfig.RestartPolicy.Name}}' \
        $(docker ps -aq) 2>/dev/null \
        || echo "# (docker not readable by this user - run snapshot.sh again"
    echo
} > "$HOSTDIR/systemd/enabled.txt"

# The boot configuration decides whether this machine starts at all, and it
# lives in /boot/firmware - outside config/ and outside /home/USER, so
# nothing else here captures it.
mkdir -p "$HOSTDIR/boot"
for f in config.txt cmdline.txt; do
    [ -f "/boot/firmware/$f" ] && cp -p "/boot/firmware/$f" "$HOSTDIR/boot/$f"
done

echo "host/: $NPROG programs, $NUNIT systemd units"
[ -n "$SKIPPED" ] && echo "host/: skipped (looks like credentials):$SKIPPED"

if [ -n "$CRONWARN" ]; then
    echo
    echo "WARNING: root's crontab was not captured and has never been captured."
    echo "         Run once as:  sudo crontab -l -u root > $HOSTDIR/crontab.root.txt"
    echo
fi

# --- commit ----------------------------------------------------------
MSG="$1"
[ -z "$MSG" ] && MSG="snapshot $(date '+%Y-%m-%d %H:%M')"

git add -A

if git diff --cached --quiet; then
    echo "Nothing changed since the last snapshot."
    exit 0
fi

echo "--- changes in this snapshot ---"
git diff --cached --stat
echo

git commit -q -m "$MSG"
echo "Committed: $MSG"

if git remote | grep -q origin; then
    git push -q origin HEAD && echo "Pushed to GitHub."
else
    echo "No remote configured yet - committed locally only."
fi
